[package]
name = "builder_derive"
version = "0.1.0"
authors = ["Daniel Akhterov <akhterovd@gmail.com>"]
edition = "2018"

[dependencies]
quote = "0.6.10"
syn = { version = "0.15.23", feature = ["derive"] }
failure = "0.1.3"
proc-macro2 = "0.4.24"
paste = "0.1.3"

[lib]
proc-macro = true
